# Generated by Django 4.1.6 on 2023-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0006_alter_match_nombre_empresa_alter_match_porcentaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirante",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="quien_me_likeo",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
