# Generated by Django 4.1.6 on 2023-03-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0007_aspirante_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirante",
            name="quien_me_likeo",
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
