# Generated by Django 4.1.6 on 2023-04-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0008_aspirante_quien_me_likeo"),
        ("app_1", "0008_habilidad"),
    ]

    operations = []
