# Generated by Django 4.1.6 on 2023-04-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0011_habilidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidad1",
            fields=[
                ("id_habilidad1", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(default="", max_length=50, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_1.usuario"
                    ),
                ),
            ],
        ),
    ]
