# Generated by Django 4.1.7 on 2023-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_archivo_delete_habilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
