# Generated by Django 4.1.6 on 2023-04-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0009_merge_0008_aspirante_quien_me_likeo_0008_habilidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ver_matchs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Nombre_empresa",
                    models.CharField(default="aaa", max_length=45, null=True),
                ),
                ("fecha_match", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_match",
                    models.CharField(
                        choices=[
                            ("Perfecto", "Perfecto"),
                            ("Muy bueno", "Muy bueno"),
                            ("Bueno", "Bueno"),
                            ("Medio", "Medio"),
                        ],
                        default="Perfecto",
                        max_length=45,
                        null=True,
                    ),
                ),
                ("porcentaje", models.PositiveIntegerField(default=100)),
                (
                    "Aspirante_id_aspirante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_1.aspirante",
                    ),
                ),
                (
                    "Empresa_id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_1.empresa"
                    ),
                ),
                (
                    "Oferta_id_oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_1.oferta"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="match",
            name="Nombre_empresa",
            field=models.CharField(default="", max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name="Habilidad",
        ),
    ]
